server:
  port: 8989
spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        
        - id: packaging-service
          uri: lb://PACKAGING-SERVICE
          predicates:
            - Path=/api/**
        - id: email-notification-service
          uri: lb://EMAIL-NOTIFICATION-SERVICE
          predicates:
            - Path=/email/**
            
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    
